supported:
  Aura\Di\Container:
    adapter: DMT\DependencyInjection\Adapters\AuraAdapter
    resolver: DMT\DependencyInjection\Resolvers\Resolver
  Aura\Di\ContainerBuilder:
    adapter: DMT\DependencyInjection\Adapters\AuraAdapter
    resolver: DMT\DependencyInjection\Resolvers\FactoryResolver
    accessor: newInstance
  DI\Container:
    adapter: DMT\DependencyInjection\Adapters\PhpDiAdapter
    resolver: DMT\DependencyInjection\Resolvers\Resolver
  Illuminate\Container\Container:
    adapter: DMT\DependencyInjection\Adapters\IlluminateAdapter
    resolver: DMT\DependencyInjection\Resolvers\Resolver
  League\Container\Container:
    adapter: DMT\DependencyInjection\Adapters\LeagueAdapter
    resolver: DMT\DependencyInjection\Resolvers\Resolver
  Pimple\Container:
    adapter: DMT\DependencyInjection\Adapters\PimpleAdapter
    resolver: DMT\DependencyInjection\Resolvers\Resolver
  Pimple\Psr11\Container:
    adapter: DMT\DependencyInjection\Adapters\PimpleAdapter
    resolver: DMT\DependencyInjection\Resolvers\PropertyResolver
    accessor: pimple
detectors:
  DMT\DependencyInjection\Detectors\InstanceOfDetector:
    supported:
      - Aura\Di\Container
      - DI\Container
      - Illuminate\Container\Container
      - League\Container\Container
      - Pimple\Container
      - Pimple\Psr11\Container
  DMT\DependencyInjection\Detectors\InstalledClassDetector:
    supported:
      - Aura\Di\ContainerBuilder
      - DI\Container
      - Illuminate\Container\Container
      - League\Container\Container
      - Pimple\Container
